### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by Tonterias** [xrgarcia/alphavantage_api_client#99]
**Is your feature request related to a problem? Please describe.**
It would be great if you can make a video explaining how to start using it. May be I am too new to python but is is giving me errors.
Traceback (most recent call last):

  File "C:\DATOS\BasuraTemporal\Portatil\Programación\Python\aplhavantage\alphavantage_api_client-main\alphavantage_api_client-main\app.py", line 1, in <module>
    from alphavantage_api_client import AlphavantageClient, GlobalQuote, Quote, AccountingReport, CompanyOverview, Ticker
  File "C:\DATOS\BasuraTemporal\Portatil\Programación\Python\aplhavantage\alphavantage_api_client-main\alphavantage_api_client-main\alphavantage_api_client\__init__.py", line 1, in <module>
    from alphavantage_api_client.client import AlphavantageClient
  File "C:\DATOS\BasuraTemporal\Portatil\Programación\Python\aplhavantage\alphavantage_api_client-main\alphavantage_api_client-main\alphavantage_api_client\client.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
PS C:\DATOS\BasuraTemporal\Portatil\Programación\Python\aplhavantage\alphavantage_api_client-main\alphavantage_api_client-main> 

**Describe the solution you'd like**
A hello world where you can get a quote and some more. 

**Describe alternatives you've considered**
Reading the wiki was not enough for me

**Additional context**
Gracias

**Comment by xrgarcia** [comment]
Hi Mike! According to the error, the ‘requests’ package is not visible to app.py. This most likely means you have not activated your environment where you installed the client. Can you confirm how you installed? Are you using pip, poetry, or something else?
